"""Run cross-correlation analysis and generate figures for the Opioids dataset.

This script performs the subject-level and group-level cross-correlation analyses of
the preprocessed Opioids dataset, then generates publication-ready figures. These
analyses are performed independently from the Pearson correlation analyses because of
the large amount of data generated by the cross-correlation maps (~10 Gb per session).
"""

from collections import ChainMap
from operator import itemgetter
from pathlib import Path
from typing import cast

import h5py as h5
import nibabel as nib
from bids import BIDSLayout
from joblib import Parallel, delayed
from rich.console import Console
from rich.progress import track

from opioids_analysis.cross_correlation import (
    SessionSubjectLevelXCorrMaps,
    compute_group_level_xcorr,
    compute_subject_level_xcorr,
    read_session_subject_level_xcorr,
    write_session_group_level_xcorr,
    write_session_subject_level_xcorr,
)
from opioids_analysis.plotting import plot_group_level_xcorr

console = Console()

########################################################################################
# Parameters
########################################################################################

params_path = Path("params/")

# Path to the preprocessed fUS-BIDS dataset.
registered_data_path = Path(
    "/mnt/feanor/datasets/opioids/derivatives/registration/derivatives/preprocessed/"
)

# Session labels present in the dataset.
sessions = ["WTM70", "WTMS1", "WTFS1", "saline", "saline2", "WTSC11"]

# Analysis results root path.
opioids_results_root = Path("/mnt/feanor/home/sdiebolt/opioids-paper-results/")

# Maximum cross-correlation lag.
max_lag = 20

# Label of the session used as control in statistical comparisons.
control_session = "salineControl"

# Threshold for significance after FDR correction.
fdr_threshold = 0.05

# Output HDF5 file for subject-level and group-level cross-correlation maps.
subject_level_path = opioids_results_root / "subject_level_xcorr.h5"
group_level_path = opioids_results_root / "group_level_xcorr.h5"

# Folder where figures will be saved.
figures_path = opioids_results_root / "figures" / "xcorr"

# Number of lags to skip when plotting (e.g., lags_to_skip=7 means plot every 8th lag).
lags_to_skip = 7

# The maximum number of concurrently running jobs. If -1 all CPUs are used.
n_jobs = -1

# Whether to overwrite existing results in HDF5 files.
overwrite_results = False

########################################################################################
# Load template and ROIs
########################################################################################

console.print("[bold cyan]Loading template and ROIs...")

template_path = params_path / "opioids_template.nii.gz"
template_img = nib.Nifti1Image.from_filename(template_path)
# Set the sform code to 0 so that Nilearn uses qform.
template_img.set_sform(None, code=0)

rois_name = params_path / "Mask-autoROIs18-slim.nii.gz"
rois_img = nib.Nifti1Image.from_filename(rois_name)

if template_img.shape != rois_img.shape:
    raise ValueError("Template and ROIs image shapes do not match!")

brain_mask_img = nib.Nifti1Image(
    (template_img.get_fdata() > 0).astype(int),
    affine=template_img.affine,
    header=template_img.header,
)

layout = BIDSLayout(registered_data_path, validate=False)

########################################################################################
# Run the subject-level cross-correlation analysis
########################################################################################

console.print("[bold cyan]Running subject-level cross-correlation analysis...")

with Parallel(n_jobs=n_jobs) as parallel:
    for session in track(sessions, description="Processing sessions", console=console):
        subjects = layout.get_subjects(session=session)
        subject_level_xcorr = parallel(
            delayed(compute_subject_level_xcorr)(
                nii_paths=sorted(
                    layout.get(subject=subject, session=session, return_type="file")
                ),
                brain_mask_img=brain_mask_img,
                rois_img=rois_img,
                max_lag=max_lag,
            )
            for subject in subjects
        )

        # Maps are saved as numpy arrays for easier operations during the group-level
        # analysis.
        xcorr_maps = [res["xcorr_maps"] for res in subject_level_xcorr]
        subject_level_xcorr = cast(
            SessionSubjectLevelXCorrMaps,
            {
                "xcorr_maps": dict(zip(subjects, xcorr_maps)),
            },
        )

        write_session_subject_level_xcorr(
            subject_level_path,
            session,
            subject_level_xcorr,
            overwrite=overwrite_results,
        )
        del subject_level_xcorr

        console.print(f"  [green]✓[/green] Completed {session}")

########################################################################################
# Create the salineControl session
########################################################################################

console.print("[bold cyan]Creating salineControl session...")

saline_sessions = ["saline", "saline2", "WTFS1", "WTMS1"]

with h5.File(subject_level_path, "r") as f:
    missing_results = [s for s in saline_sessions if s not in f["xcorr_maps"]]

if missing_results:
    raise RuntimeError(
        "The following saline cross-correlation maps are missing from the HDF5 file: "
        f"{missing_results}."
    )

saline_xcorr = [
    read_session_subject_level_xcorr(subject_level_path, s) for s in saline_sessions
]

saline_control_xcorr = cast(
    SessionSubjectLevelXCorrMaps,
    {"xcorr_maps": dict(ChainMap(*map(itemgetter("xcorr_maps"), saline_xcorr)))},
)
del saline_xcorr

write_session_subject_level_xcorr(
    subject_level_path,
    control_session,
    saline_control_xcorr,
    overwrite=overwrite_results,
)
del saline_control_xcorr

console.print("  [green]✓[/green] salineControl session created")

########################################################################################
# Run the group-level cross-correlation analysis
########################################################################################

console.print("[bold cyan]Running group-level cross-correlation analysis...")

brain_mask = brain_mask_img.get_fdata().squeeze().astype(bool)

with h5.File(subject_level_path, "r") as f:
    sessions = list(f["xcorr_maps"].keys())

for session in track(sessions, description="Processing sessions", console=console):
    group_level_xcorr = compute_group_level_xcorr(
        subject_level_path=subject_level_path,
        session_treatment=session,
        session_control=control_session,
        brain_mask=brain_mask,
        fdr_threshold=fdr_threshold,
        n_jobs=n_jobs,
    )

    write_session_group_level_xcorr(
        group_level_path, session, group_level_xcorr, overwrite=overwrite_results
    )
    console.print(f"  [green]✓[/green] Completed {session}")

########################################################################################
# Plot the group-level cross-correlation figures
########################################################################################

console.print("[bold cyan]Plotting group-level cross-correlation figures...")

figures_path.mkdir(exist_ok=True, parents=True)

with h5.File(group_level_path, "r") as f:
    sessions = list(f["xcorr_maps"].keys())

_ = Parallel(n_jobs=n_jobs)(
    delayed(plot_group_level_xcorr)(
        group_level_path=group_level_path,
        session=session,
        template_img=template_img,
        rois_img=rois_img,
        lags_to_skip=lags_to_skip,
        output_path=figures_path,
    )
    for session in track(sessions, description="Generating plots")
)

console.print("[bold green]✓ Cross-correlation analysis complete!")
console.print(f"[bold green]✓ Figures saved to {figures_path}")
